FROM python:3.9

# Set the working directory
WORKDIR /app

# Install virtualenv
RUN pip install virtualenv

# Create a virtual environment outside the /app directory
RUN virtualenv /venv

# Copy the requirements file
COPY requirements.txt .

# Activate the virtual environment and install requirements
RUN /venv/bin/pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Set environment variables for the virtual environment
ENV VIRTUAL_ENV=/venv
ENV PATH="/venv/bin:$PATH"

# Set the command to run the FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
